# Week 04 - Lecture 02 (Guest Lecturer Paul Murrell)

## Rough Agenda

### **2:05 pm - 3:55 pm** 

 + Data visualization 
 + Plot roast (@sec-roast)
 + Create your own (@sec-plot)
    
### Before we begin **sort yourselves into groups** following @sec-groups

:::{.callout-warning icon=false}
## <i class="fa fa-question-circle" aria-hidden="true"></i> <i class="fa fa-users" aria-hidden="true"></i> <i class="fa fa-pencil-square" aria-hidden="true"></i> Quick [StatChat](https://canvas.auckland.ac.nz/courses/141056/external_tools/38296) Poll!

In [StatChat](https://canvas.auckland.ac.nz/courses/141056/external_tools/38296), vote whether you think the mock assignment AI-use statement below is **adequate** or **inadequate**.

> I used ChatGPT only to assist with improving the clarity of my writing and to support my understanding of some code. All ideas, analyses, and work submitted are my own, and no AI was used to generate substantive content or complete the assignment.

:::


::: {.callout-tip}
## Data Viz is key
 - Interpret, critique and communicate using visualization! 
:::

## Data visualization 

*In-class content*


## Roast your lecturer's plot {#sec-roast}

Figure 1 in @swift shows which "surprise" dresses were worn during which concerts in Taylor Swift's Eras Tour.  According to the text of the article, Figure 1 is supposed to show:

* that there were different legs of the tour.
* the relative lengths of the different legs of the tour.
* the number of concerts in each leg of the tour.
* the density of concerts in each leg of the tour.
* which dresses were used in each concert.
* the proportion of concerts that each dress was used for.
* that the dresses in the European leg were new (not used in previous legs).  
* ditto for the North American leg.
* that several new albums were released during the tour.

**In your groups** take a look at [Figure 1](https://academic.oup.com/view-large/figure/544225503/qmaf093f01.jpg) and **roast** (yes you can be as mean as you like, honestly) or admire it^[Note that your lecturer is an author of the publication and she consents to the roasting!] You will have no doubt read and digested [this section of the course guide](https://biosci738.github.io/BIOSCI738/data-visualization.html), so you will have some basis for critiquing the plot.

**Be prepared to discuss your progress/thoughts as we wander around the class.**

:::{.callout-warning icon=false}
## <i class="fa fa-question-circle" aria-hidden="true"></i> <i class="fa fa-users" aria-hidden="true"></i> <i class="fa fa-pencil-square" aria-hidden="true"></i> Plot Roast!

Once you've come to a consensus (or not ;)), open [StatChat](https://canvas.auckland.ac.nz/courses/141056/external_tools/38296) and **individually** write out your Figure 1 roasts (aka critiques).
:::


## Plot your own Swift story {#sec-plot}


The code below (*which will open given a keyword*) creates the figure you've been roasting. Now it's your turn to follow through on your critiques. Using the code below as a baseline (*if you wish*) create a new and improved version of [Figure 1](https://academic.oup.com/view-large/figure/544225503/qmaf093f01.jpg). 


**Be prepared to show us your progress as we wander around the class!** Remember to take the opportunity to pick Paul's brain!

Pay attention for the keyword to unlock what's below!

<input type="text" id="secretInput" placeholder="Enter keyword here">
<button onclick="checkKeyword()">💃 Unlock the code 💃</button>

<div id="hiddenContent" style="display:none; margin-top:10px;">

First you will need to download [these data](https://canvas.auckland.ac.nz/courses/141056/files/17296870/download?download_frd=1) into your working directory.
  
```{r, eval = FALSE}

#############
## packages
require(ggplot2)
require(ggimage)
require(cowplot)
require(extrafont)
extrafont::loadfonts()
require(forcats)
require(dplyr)
##############
## data
load("swift.RData")
##############

## reorder data according to
## first appearance

first_dates <- oneRowPerConcert %>%
  group_by(DressName) %>%
  summarise(first_date = min(Date), .groups = "drop")

oneRowPerConcert <- oneRowPerConcert %>%
  left_join(first_dates, by = "DressName") %>%
  mutate(DressName = fct_reorder(DressName, first_date)) %>%
  select(-first_date)

outfits <- outfits %>%
  left_join(first_dates, by = "DressName") %>%
  mutate(DressName = fct_reorder(DressName, first_date)) %>%
  select(-first_date)

##################
### Figure 1 #####
##################

max_dress_level <- length(unique((oneRowPerConcert$DressName)))


main_plot <- ggplot(oneRowPerConcert, aes(x = Date, y = DressName, colour = ColourHex1)) +
    geom_point(size = 4, alpha = 1) +
    scale_colour_identity() +
    theme_minimal() +
    labs(x = "", y = "") +
    geom_rect(aes(xmin = as.Date("2023-08-28"), xmax = as.Date("2023-11-08"),
                  ymin = -Inf, ymax = Inf), fill = "gray", alpha = 0.01, colour = NA) +
    geom_rect(aes(xmin = as.Date("2023-11-27"), xmax = as.Date("2024-02-06"),
                  ymin = -Inf, ymax = Inf), fill = "gray", alpha = 0.01, colour = NA) +  
    geom_rect(aes(xmin = as.Date("2024-03-10"), xmax = as.Date("2024-05-08"),
                  ymin = -Inf, ymax = Inf), fill = "gray", alpha = 0.01, colour = NA) +
    geom_rect(aes(xmin = as.Date("2024-08-21"), xmax = as.Date("2024-10-17"),
                  ymin = -Inf, ymax = Inf), fill = "gray", alpha = 0.01, colour = NA) +
    geom_vline(xintercept = as.Date("2024-05-09"), linetype = "dashed", colour = "black") +
    geom_vline(xintercept = as.Date("2023-03-17"), linetype = "dashed", colour = "black") +
    geom_vline(xintercept = as.Date("2024-10-18"), linetype = "dashed", colour = "black") +
    geom_vline(xintercept = as.Date("2023-08-24"), linetype = "dashed", colour = "black") +
    geom_vline(xintercept = as.Date("2024-02-07"), linetype = "dashed", colour = "black") +
    geom_vline(xintercept = as.Date("2024-04-16"), linetype = "solid", colour = "darkgray", linewidth = 2) +
    geom_vline(xintercept = as.Date("2023-07-07"), linetype = "solid", colour = "purple", linewidth = 2) +
    geom_vline(xintercept = as.Date("2023-10-27"), linetype = "solid", colour = "blue", linewidth = 2) +
    annotate("text", x = as.Date("2024-05-09"), y = max_dress_level, 
             label = "Europeᵃ", colour = "black", angle = -90, vjust = -0.5, family = "Calibri", size = 6,
             lineheight = 0.6) +
    annotate("text", x = as.Date("2023-03-17"), y = max_dress_level, 
             label = "United\n Statesᵃ", colour = "black", angle = -90, vjust = -0.2, family = "Calibri",
             size = 6, lineheight = 0.6) +
    annotate("text", x = as.Date("2024-10-18"), y = max_dress_level, 
             label = "North\n Americaᵃ", colour = "black", angle = -90, vjust = -0.2, family = "Calibri",
             size = 6, lineheight = 0.6) +
    annotate("text", x = as.Date("2023-08-24"), y = max_dress_level, 
             label = "Latin\n Americaᵃ", colour = "black", angle = -90, vjust = -0.2, family = "Calibri",
             size = 6, lineheight = 0.6) +
    annotate("text", x = as.Date("2024-02-07"), y = max_dress_level, 
             label = "Asia/\n Oceaniaᵃ", colour = "black", angle = -90, vjust = -0.2, family = "Calibri",
             size = 6, lineheight = 0.6) +
    annotate("text", x = as.Date("2024-04-16"), y = max_dress_level, 
             label = "TTPDᵇ", colour = "darkgray", angle = -90, vjust = -0.5, family = "Calibri", size = 6,
             lineheight = 0.6,
             fontface = "bold") +
    annotate("text", x = as.Date("2023-07-07"), y = max_dress_level, 
             label = "    Speak Now\nTVᵇ", colour = "purple", angle = -90, vjust = -0.2, family = "Calibri",
             size = 6, lineheight = 0.6) +
    annotate("text", x = as.Date("2023-10-27"), y = max_dress_level, 
             label = "1989\nTVᵇ", colour = "blue", angle = -90, vjust = -0.2, family = "Calibri", size = 6,
             lineheight = 0.6) +
    scale_x_date(date_labels = "%b %Y", date_breaks = "3 months") +
    theme(axis.text.x = element_text(angle = 0, hjust = 1, size = 16),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          plot.title = element_text(hjust=0.5, size = 14, margin = margin(b = 20), face = "bold"),
          plot.margin = margin(t = 0, r = 0, b = 10, l = 0),
          text = element_text(colour = "black", family = "Calibri", size = 16))

count_plot <- ggplot(outfits, aes(x = n, y = DressName, fill = DressName)) +
  geom_bar(stat = "identity", width = 0.8) +
  geom_image(
    aes(image = imagePath, x = n),  
    size = 0.095,                    
    nudge_x = 0.5,
    by = "height") +
  geom_text(
    aes(x = n + 3, label = paste0(n, " (", round(percentage, 1), "%) - ", DressName)),  
    hjust = 0,
    nudge_x = 3.5,
    colour = "black",
    size = 6,
    family = "Calibri") +
  scale_fill_manual(values = colorPaletteDresses) +
  theme_minimal() +
  labs(title = "", x = "", y = "") +
  theme(
    axis.text = element_blank(),
    axis.ticks = element_blank(),  
    plot.title = element_text(hjust = 0.5, size = 12),
    legend.position = "none",
    plot.margin = margin(t = 0, r = 0, b = 10, l = 0),
    text = element_text(colour = "black", family = "Calibri", size = 16)) +
  xlim(0, 65)   


plot_grid(
  count_plot, main_plot,
  ncol = 2,
  align = "h",
  axis = "tb",
  rel_widths = c(2, 3))

```

</div>

<script>
function checkKeyword() {
  var input = document.getElementById("secretInput").value;
  var keyword = "Florida!!!"; 
  
  if (input === keyword) {
    document.getElementById("hiddenContent").style.display = "block";
  } else {
    alert("Incorrect keyword!");
  }
}
</script>

:::{.callout-warning icon=false}
## <i class="fa fa-question-circle" aria-hidden="true"></i> <i class="fa fa-users" aria-hidden="true"></i> <i class="fa fa-pencil-square" aria-hidden="true"></i> New and improved!

By the end of class add your plot (*irrespective of how far you've gotten*) to this shared [Google Doc](https://docs.google.com/document/d/1trZvluBE-JxnI8_m47x_0_r_tUyjU-VvILjOT-RM3RE/edit?usp=sharing)!

By the end of the week, to the `tasks` folder of your GitHub repository include, add and push a **fully reproducible** `R` script named `week_04.r` that creates your new and improved version of the Figure we've been critiquing. You can of course use the code you *unlocked* above as a starting point. Remember to **include any required data** & update your `README.md` accordingly!


:::
