# Additional


### Visualizing multivariate data

In your groups work through the code below that visualizes different Pokémon stats. Discuss, how useful do you find each plot and be prepared to answer questions as I wander around the class!

```{r, eval = FALSE}
require(tidyverse)
require(GGally)
url <- "https://raw.githubusercontent.com/STATS-UOA/databunker/master/data/pokemon.csv"
data <- read_csv(url)
## pairs plots for continuous variables
data %>%
  select(where(is.numeric)) |> pairs()
data %>%
  select(where(is.numeric)) |> ggpairs()
## but what if you had a categorical variable
data %>%
  select(legendary, where(is.numeric)) |> ggpairs(aes(color = legendary))
## two (or more) categorical variables
with(data, table(legendary,
    type2)) |> barplot(legend = TRUE)
## conditional
with(data, prop.table(table(legendary,
    type2), margin = 2)) |> barplot(legend = TRUE)
## alluvial plots
require(alluvial)
data$Freq <- 1
mult <- aggregate(Freq ~ type2 + legendary,
    data = data, FUN = sum)
alluvial(mult, freq = mult$Freq, border = NA, col = ifelse(mult$legendary, "red", "blue"))
## What are some potential interpretation pitfalls
## heatmaps
library(pheatmap)
data %>%
  select(where(is.numeric), -Freq, - generation, -number) |> cor() |>
  pheatmap( cluster_rows = TRUE, cluster_cols = TRUE,
    treeheight_row = 0, treeheight_col = 0)
data %>% select(where(is.numeric), -Freq, -generation, -number) |>
  pheatmap( , cluster_rows = TRUE,
    cluster_cols = TRUE, labels_row = data$name, cex = 0.7)
## look at ?pheatmap
library(corrplot)
data %>% select(where(is.numeric), -Freq, - generation, -number) |> cor() |> 
  corrplot(addrect = 3, order = 'hclust')

```


## Casestudies {#sec-mdscasestudies02}

 Revisit one of the following case studies. Create an informative visualization that appropriately demonstrates the structure of these multivariate data. You may find some useful examples [here](https://epurdom.github.io/Stat131A/book/visualizing-multivariate-data.html#relationships-between-continous-variables).

 1. **Eigenfaces** from @sec-eigenfaces
 2. **Clusterducks** from @sec-clusterducks
 3. **Bird Abundance** first case study from revisited in @sec-mdscasestudies (data from @birds)
 4. **DNA** second case study from @sec-mdscasestudies (data from @dna)
 
**Be prepared to present your activity to me as I'll be prepared to critique!**



## Q&A and peer-share {#sec-peershare19}

:::{.callout-warning icon=false}
## <i class="fa fa-question-circle" aria-hidden="true"></i> <i class="fa fa-users" aria-hidden="true"></i> <i class="fa fa-pencil-square" aria-hidden="true"></i> Peer-Share
Go over an activity from the class again. Feel free to ask Charlotte a question or two about it!
:::