# Week 12 - Lecture 01

## Rough Agenda

### **2:05 pm - 3:30 pm** 

(*We will finish a little early to accommodate those with IOAs, note there will be no office hour after this lecture for the same reason*)


::: {.callout-note}
## Don't forget to fill out your SETs!
:::

:::{.callout-warning icon=false}
## <i class="fa fa-question-circle" aria-hidden="true"></i> <i class="fa fa-users" aria-hidden="true"></i> <i class="fa fa-pencil-square" aria-hidden="true"></i> Guest seminar

Ask Ben a question via  [StatChat](https://canvas.auckland.ac.nz/courses/141056/external_tools/38296) or in person!

**Speaker:** Dr Ben Stevenson

**Title:** Capture-mark-recapture without capturing, marking, or recapturing

**Abstract:** Traditional applications of capture-mark-recapture to wildlife surveys work something like this: researchers capture animals, mark them with a tag, recapture and recognise them on successive occasions later on, and finally use a statistical model to estimate the size of the wildlife population. Times have changed! The field of ecological statistics has come a long way in recent decades, to such an extent that the term “capture-mark-recapture” is a bit of a misnomer. We can conduct capture-mark-recapture studies without capturing animals, without marking them, and without recognising when an individual has been recaptured. We can estimate much more than abundance of a population: we can gain insights into population dynamics, spatial distribution, and other complex ecological processes. We can use these models to understand populations beyond the animal kingdom. In this talk, I will take you on a worldwide tour of some capture-recapture problems I have worked on, with illustrative applications to animal (and not-so-animal) populations around the globe. Our stops will include visiting manta rays in Indonesia, snow leopards in Mongolia, owls in North America, cord-forming basidiomycetes in a Welsh forest, and a flock of friendly chickens a little closer to home.


:::



:::{.callout-warning icon=false}
## <i class="fa fa-question-circle" aria-hidden="true"></i> <i class="fa fa-users" aria-hidden="true"></i> <i class="fa fa-pencil-square" aria-hidden="true"></i> Hwyr Fawr!

And that's the end of BIOSCI 738 2026 (*apart from those final few assignments of course!*)

As the course has come to an end, write a [self-reflection](https://canvas.auckland.ac.nz/courses/141056/assignments/490669) focusing on your learning experience during the course, outlining the development of your statistical and programming skills (see the [week 12](https://canvas.auckland.ac.nz/courses/141056/assignments/490669) task on CANVAS for more details).

:::